// Auto-generated. Do not edit!

// (in-package dji_sdk.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LocalPositionNavigationFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.x_progress = null;
      this.y_progress = null;
      this.z_progress = null;
    }
    else {
      if (initObj.hasOwnProperty('x_progress')) {
        this.x_progress = initObj.x_progress
      }
      else {
        this.x_progress = 0;
      }
      if (initObj.hasOwnProperty('y_progress')) {
        this.y_progress = initObj.y_progress
      }
      else {
        this.y_progress = 0;
      }
      if (initObj.hasOwnProperty('z_progress')) {
        this.z_progress = initObj.z_progress
      }
      else {
        this.z_progress = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LocalPositionNavigationFeedback
    // Serialize message field [x_progress]
    bufferOffset = _serializer.uint8(obj.x_progress, buffer, bufferOffset);
    // Serialize message field [y_progress]
    bufferOffset = _serializer.uint8(obj.y_progress, buffer, bufferOffset);
    // Serialize message field [z_progress]
    bufferOffset = _serializer.uint8(obj.z_progress, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LocalPositionNavigationFeedback
    let len;
    let data = new LocalPositionNavigationFeedback(null);
    // Deserialize message field [x_progress]
    data.x_progress = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [y_progress]
    data.y_progress = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [z_progress]
    data.z_progress = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 3;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk/LocalPositionNavigationFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dc1f44f25fca6f00e17022e1b8cc9f3e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #progress is in percent
    uint8 x_progress 
    uint8 y_progress 
    uint8 z_progress 
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LocalPositionNavigationFeedback(null);
    if (msg.x_progress !== undefined) {
      resolved.x_progress = msg.x_progress;
    }
    else {
      resolved.x_progress = 0
    }

    if (msg.y_progress !== undefined) {
      resolved.y_progress = msg.y_progress;
    }
    else {
      resolved.y_progress = 0
    }

    if (msg.z_progress !== undefined) {
      resolved.z_progress = msg.z_progress;
    }
    else {
      resolved.z_progress = 0
    }

    return resolved;
    }
};

module.exports = LocalPositionNavigationFeedback;
