// Auto-generated. Do not edit!

// (in-package dji_sdk_web_groundstation.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let dji_sdk = _finder('dji_sdk');

//-----------------------------------------------------------

class WebWaypointReceiveGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.waypoint_list = null;
      this.tid = null;
    }
    else {
      if (initObj.hasOwnProperty('waypoint_list')) {
        this.waypoint_list = initObj.waypoint_list
      }
      else {
        this.waypoint_list = new dji_sdk.msg.WaypointList();
      }
      if (initObj.hasOwnProperty('tid')) {
        this.tid = initObj.tid
      }
      else {
        this.tid = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type WebWaypointReceiveGoal
    // Serialize message field [waypoint_list]
    bufferOffset = dji_sdk.msg.WaypointList.serialize(obj.waypoint_list, buffer, bufferOffset);
    // Serialize message field [tid]
    bufferOffset = _serializer.uint64(obj.tid, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type WebWaypointReceiveGoal
    let len;
    let data = new WebWaypointReceiveGoal(null);
    // Deserialize message field [waypoint_list]
    data.waypoint_list = dji_sdk.msg.WaypointList.deserialize(buffer, bufferOffset);
    // Deserialize message field [tid]
    data.tid = _deserializer.uint64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += dji_sdk.msg.WaypointList.getMessageSize(object.waypoint_list);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk_web_groundstation/WebWaypointReceiveGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6ec8abdbbe8f44dcf91e84ea5b8df4d8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    dji_sdk/WaypointList waypoint_list
    #task id
    uint64 tid
    
    ================================================================================
    MSG: dji_sdk/WaypointList
    Waypoint[] waypoint_list
    
    ================================================================================
    MSG: dji_sdk/Waypoint
    #latitude is in degree
    float64 latitude
    #longitude is in degree
    float64 longitude
    float32 altitude
    #heading is in [-180,180]
    int16 heading 
    #stay time is in second
    uint16 staytime
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new WebWaypointReceiveGoal(null);
    if (msg.waypoint_list !== undefined) {
      resolved.waypoint_list = dji_sdk.msg.WaypointList.Resolve(msg.waypoint_list)
    }
    else {
      resolved.waypoint_list = new dji_sdk.msg.WaypointList()
    }

    if (msg.tid !== undefined) {
      resolved.tid = msg.tid;
    }
    else {
      resolved.tid = 0
    }

    return resolved;
    }
};

module.exports = WebWaypointReceiveGoal;
