// Auto-generated. Do not edit!

// (in-package dji_sdk_web_groundstation.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class WebWaypointReceiveFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.latitude_progress = null;
      this.longitude_progress = null;
      this.altitude_progress = null;
      this.index_progress = null;
      this.stage = null;
    }
    else {
      if (initObj.hasOwnProperty('latitude_progress')) {
        this.latitude_progress = initObj.latitude_progress
      }
      else {
        this.latitude_progress = 0;
      }
      if (initObj.hasOwnProperty('longitude_progress')) {
        this.longitude_progress = initObj.longitude_progress
      }
      else {
        this.longitude_progress = 0;
      }
      if (initObj.hasOwnProperty('altitude_progress')) {
        this.altitude_progress = initObj.altitude_progress
      }
      else {
        this.altitude_progress = 0;
      }
      if (initObj.hasOwnProperty('index_progress')) {
        this.index_progress = initObj.index_progress
      }
      else {
        this.index_progress = 0;
      }
      if (initObj.hasOwnProperty('stage')) {
        this.stage = initObj.stage
      }
      else {
        this.stage = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type WebWaypointReceiveFeedback
    // Serialize message field [latitude_progress]
    bufferOffset = _serializer.uint8(obj.latitude_progress, buffer, bufferOffset);
    // Serialize message field [longitude_progress]
    bufferOffset = _serializer.uint8(obj.longitude_progress, buffer, bufferOffset);
    // Serialize message field [altitude_progress]
    bufferOffset = _serializer.uint8(obj.altitude_progress, buffer, bufferOffset);
    // Serialize message field [index_progress]
    bufferOffset = _serializer.uint8(obj.index_progress, buffer, bufferOffset);
    // Serialize message field [stage]
    bufferOffset = _serializer.uint8(obj.stage, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type WebWaypointReceiveFeedback
    let len;
    let data = new WebWaypointReceiveFeedback(null);
    // Deserialize message field [latitude_progress]
    data.latitude_progress = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [longitude_progress]
    data.longitude_progress = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [altitude_progress]
    data.altitude_progress = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [index_progress]
    data.index_progress = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [stage]
    data.stage = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk_web_groundstation/WebWaypointReceiveFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0895e5924b05e8720f48006b778b54ce';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #progress is in percent
    uint8 latitude_progress
    uint8 longitude_progress
    uint8 altitude_progress
    uint8 index_progress
    #stage code:
    #  0: waiting for waypoint_list
    #  1: waiting for start
    #  2: in progress
    #  3: paused
    #  4: canceled
    uint8 stage
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new WebWaypointReceiveFeedback(null);
    if (msg.latitude_progress !== undefined) {
      resolved.latitude_progress = msg.latitude_progress;
    }
    else {
      resolved.latitude_progress = 0
    }

    if (msg.longitude_progress !== undefined) {
      resolved.longitude_progress = msg.longitude_progress;
    }
    else {
      resolved.longitude_progress = 0
    }

    if (msg.altitude_progress !== undefined) {
      resolved.altitude_progress = msg.altitude_progress;
    }
    else {
      resolved.altitude_progress = 0
    }

    if (msg.index_progress !== undefined) {
      resolved.index_progress = msg.index_progress;
    }
    else {
      resolved.index_progress = 0
    }

    if (msg.stage !== undefined) {
      resolved.stage = msg.stage;
    }
    else {
      resolved.stage = 0
    }

    return resolved;
    }
};

module.exports = WebWaypointReceiveFeedback;
