(cl:defpackage dji_sdk_web_groundstation-msg
  (:use )
  (:export
   "<MAPNAVSRVCMD>"
   "MAPNAVSRVCMD"
   "<WEBWAYPOINTRECEIVEACTION>"
   "WEBWAYPOINTRECEIVEACTION"
   "<WEBWAYPOINTRECEIVEACTIONFEEDBACK>"
   "WEBWAYPOINTRECEIVEACTIONFEEDBACK"
   "<WEBWAYPOINTRECEIVEACTIONGOAL>"
   "WEBWAYPOINTRECEIVEACTIONGOAL"
   "<WEBWAYPOINTRECEIVEACTIONRESULT>"
   "WEBWAYPOINTRECEIVEACTIONRESULT"
   "<WEBWAYPOINTRECEIVEFEEDBACK>"
   "WEBWAYPOINTRECEIVEFEEDBACK"
   "<WEBWAYPOINTRECEIVEGOAL>"
   "WEBWAYPOINTRECEIVEGOAL"
   "<WEBWAYPOINTRECEIVERESULT>"
   "WEBWAYPOINTRECEIVERESULT"
  ))

